import type { DomainStandard } from "../domain-standards";

export const fhirPatientIntake: DomainStandard = {
  id: "fhir-patient-intake",
  name: "FHIR Patient Intake R4",
  domain: "healthcare",
  version: "R4 (4.0.1)",
  description:
    "HL7 FHIR Patient resource and Questionnaire profile for patient intake forms. Defines required demographic fields, identifiers, and value sets for clinical data collection.",
  url: "https://hl7.org/fhir/R4/patient.html",
  keywords: [
    "patient",
    "intake",
    "clinical",
    "healthcare",
    "medical",
    "hospital",
    "clinic",
    "health",
    "fhir",
    "hl7",
    "ehr",
    "electronic health record",
    "admission",
    "registration",
    "demographic",
    "diagnosis",
    "treatment",
    "physician",
    "doctor",
    "nurse",
    "prescription",
    "orthopedic",
    "surgery",
    "surgical",
    "rehabilitation",
    "department",
    "medication",
    "allergy",
    "emergency",
    "outpatient",
    "inpatient",
    "radiology",
    "laboratory",
    "oncology",
    "cardiology",
    "pediatric",
    "neurology",
    "physiotherapy",
    "therapy",
    "patient record",
  ],
  fieldConstraints: [
    {
      fieldKey: "familyName",
      label: "Family Name",
      type: "string",
      required: "mandatory",
      description:
        "Patient's family (last) name. Required for patient identification.",
      standardReference: "FHIR Patient.name.family",
    },
    {
      fieldKey: "givenName",
      label: "Given Name",
      type: "string",
      required: "mandatory",
      description:
        "Patient's given (first) name. Required for patient identification.",
      standardReference: "FHIR Patient.name.given",
    },
    {
      fieldKey: "birthDate",
      label: "Date of Birth",
      type: "date",
      required: "mandatory",
      description:
        "Patient's date of birth. Required for age verification and clinical decision support.",
      standardReference: "FHIR Patient.birthDate",
    },
    {
      fieldKey: "gender",
      label: "Administrative Gender",
      type: "select",
      required: "mandatory",
      description:
        "Administrative gender used for record-keeping, not clinical gender identity.",
      codeSystemId: "administrative-gender",
      validationRules: {
        options: ["male", "female", "other", "unknown"],
      },
      standardReference: "FHIR Patient.gender",
    },
    {
      fieldKey: "identifier",
      label: "Patient Identifier",
      type: "string",
      required: "mandatory",
      description:
        "A unique identifier for the patient (e.g., MRN, SSN, national ID).",
      standardReference: "FHIR Patient.identifier",
    },
    {
      fieldKey: "phone",
      label: "Phone Number",
      type: "string",
      required: "recommended",
      description: "Patient's contact phone number for communication.",
      validationRules: {
        pattern: "^[+]?[\\d\\s()-]+$",
      },
      standardReference: "FHIR Patient.telecom (phone)",
    },
    {
      fieldKey: "email",
      label: "Email Address",
      type: "email",
      required: "recommended",
      description: "Patient's email address for electronic communication.",
      standardReference: "FHIR Patient.telecom (email)",
    },
    {
      fieldKey: "addressLine",
      label: "Address",
      type: "string",
      required: "recommended",
      description: "Street address line for the patient's home address.",
      standardReference: "FHIR Patient.address.line",
    },
    {
      fieldKey: "city",
      label: "City",
      type: "string",
      required: "recommended",
      description: "City component of the patient's address.",
      standardReference: "FHIR Patient.address.city",
    },
    {
      fieldKey: "postalCode",
      label: "Postal Code",
      type: "string",
      required: "recommended",
      description: "Postal/ZIP code for the patient's address.",
      standardReference: "FHIR Patient.address.postalCode",
    },
    {
      fieldKey: "maritalStatus",
      label: "Marital Status",
      type: "select",
      required: "optional",
      description:
        "Patient's marital status, relevant for next-of-kin and insurance.",
      codeSystemId: "marital-status",
      validationRules: {
        options: [
          "Annulled",
          "Divorced",
          "Interlocutory",
          "Legally Separated",
          "Married",
          "Polygamous",
          "Never Married",
          "Domestic Partner",
          "Unmarried",
          "Widowed",
          "Unknown",
        ],
      },
      standardReference: "FHIR Patient.maritalStatus",
    },
    {
      fieldKey: "emergencyContactName",
      label: "Emergency Contact Name",
      type: "string",
      required: "recommended",
      description: "Name of the patient's emergency contact person.",
      standardReference: "FHIR Patient.contact.name",
    },
    {
      fieldKey: "emergencyContactPhone",
      label: "Emergency Contact Phone",
      type: "string",
      required: "recommended",
      description: "Phone number of the emergency contact.",
      standardReference: "FHIR Patient.contact.telecom",
    },
    {
      fieldKey: "preferredLanguage",
      label: "Preferred Language",
      type: "select",
      required: "optional",
      description: "Patient's preferred language for communication.",
      codeSystemId: "languages",
      validationRules: {
        options: [
          "English",
          "Spanish",
          "French",
          "German",
          "Chinese",
          "Japanese",
          "Korean",
          "Arabic",
          "Portuguese",
          "Russian",
          "Other",
        ],
      },
      standardReference: "FHIR Patient.communication.language",
    },
    {
      fieldKey: "active",
      label: "Record Active",
      type: "boolean",
      required: "optional",
      description:
        "Whether this patient record is in active use. Defaults to true.",
      standardReference: "FHIR Patient.active",
    },
  ],
  codeSystems: [
    {
      id: "administrative-gender",
      name: "FHIR AdministrativeGender",
      values: [
        { code: "male", display: "Male" },
        { code: "female", display: "Female" },
        { code: "other", display: "Other" },
        { code: "unknown", display: "Unknown" },
      ],
    },
    {
      id: "marital-status",
      name: "HL7 v3 MaritalStatus",
      values: [
        { code: "A", display: "Annulled" },
        { code: "D", display: "Divorced" },
        { code: "I", display: "Interlocutory" },
        { code: "L", display: "Legally Separated" },
        { code: "M", display: "Married" },
        { code: "P", display: "Polygamous" },
        { code: "S", display: "Never Married" },
        { code: "T", display: "Domestic Partner" },
        { code: "U", display: "Unmarried" },
        { code: "W", display: "Widowed" },
        { code: "UNK", display: "Unknown" },
      ],
    },
    {
      id: "languages",
      name: "BCP-47 Common Languages",
      values: [
        { code: "en", display: "English" },
        { code: "es", display: "Spanish" },
        { code: "fr", display: "French" },
        { code: "de", display: "German" },
        { code: "zh", display: "Chinese" },
        { code: "ja", display: "Japanese" },
        { code: "ko", display: "Korean" },
        { code: "ar", display: "Arabic" },
        { code: "pt", display: "Portuguese" },
        { code: "ru", display: "Russian" },
      ],
    },
  ],
  exportFormats: ["fhir-questionnaire-json", "json-schema"],
};
