import type { DomainStandard } from "../domain-standards";

export const schemaOrgJobPosting: DomainStandard = {
  id: "schema-org-job-posting",
  name: "Schema.org JobPosting",
  domain: "recruitment",
  version: "Schema.org 26.0",
  description:
    "Schema.org JobPosting vocabulary for structuring job listings and application forms. Enables machine-readable job postings in JSON-LD format for search engines and job boards.",
  url: "https://schema.org/JobPosting",
  keywords: [
    "job",
    "hiring",
    "application",
    "recruit",
    "position",
    "employment",
    "career",
    "resume",
    "cv",
    "candidate",
    "job posting",
    "job application",
    "sales representative",
  ],
  fieldConstraints: [
    {
      fieldKey: "jobTitle",
      label: "Job Title",
      type: "string",
      required: "mandatory",
      description: "The title of the job position being advertised.",
      standardReference: "Schema.org JobPosting.title",
    },
    {
      fieldKey: "hiringOrganization",
      label: "Hiring Organization",
      type: "string",
      required: "mandatory",
      description: "The organization offering the job position.",
      standardReference: "Schema.org JobPosting.hiringOrganization",
    },
    {
      fieldKey: "employmentType",
      label: "Employment Type",
      type: "select",
      required: "mandatory",
      description: "Type of employment (full-time, part-time, contract, etc.).",
      codeSystemId: "schema-org-employment-type",
      validationRules: {
        options: ["FULL_TIME", "PART_TIME", "CONTRACT", "TEMPORARY", "INTERN"],
      },
      standardReference: "Schema.org JobPosting.employmentType",
    },
    {
      fieldKey: "jobDescription",
      label: "Job Description",
      type: "string",
      required: "mandatory",
      description: "A description of the job, including responsibilities and expectations.",
      standardReference: "Schema.org JobPosting.description",
    },
    {
      fieldKey: "experienceRequirements",
      label: "Experience Requirements",
      type: "string",
      required: "recommended",
      description:
        "Description of skills and experience required or preferred for the position.",
      standardReference: "Schema.org JobPosting.experienceRequirements",
    },
    {
      fieldKey: "skills",
      label: "Required Skills",
      type: "string",
      required: "recommended",
      description: "A statement of knowledge, skill, ability, or personal attribute required.",
      standardReference: "Schema.org JobPosting.skills",
    },
    {
      fieldKey: "qualifications",
      label: "Qualifications",
      type: "string",
      required: "recommended",
      description:
        "Specific qualifications required for the position (education, certifications).",
      standardReference: "Schema.org JobPosting.qualifications",
    },
    {
      fieldKey: "jobLocation",
      label: "Job Location",
      type: "string",
      required: "recommended",
      description: "The location(s) where the job can be performed.",
      standardReference: "Schema.org JobPosting.jobLocation",
    },
    {
      fieldKey: "baseSalary",
      label: "Base Salary",
      type: "string",
      required: "optional",
      description: "The base salary of the job or of an employee in the proposed role.",
      standardReference: "Schema.org JobPosting.baseSalary",
    },
    {
      fieldKey: "datePosted",
      label: "Date Posted",
      type: "date",
      required: "recommended",
      description: "Publication date of the job posting.",
      standardReference: "Schema.org JobPosting.datePosted",
    },
    {
      fieldKey: "validThrough",
      label: "Valid Through",
      type: "date",
      required: "optional",
      description: "The date after which the job posting is no longer valid.",
      standardReference: "Schema.org JobPosting.validThrough",
    },
    {
      fieldKey: "applicationContact",
      label: "Application Contact",
      type: "string",
      required: "optional",
      description: "Contact information for submitting applications.",
      standardReference: "Schema.org JobPosting.applicationContact",
    },
  ],
  codeSystems: [
    {
      id: "schema-org-employment-type",
      name: "Schema.org EmploymentType",
      values: [
        { code: "FULL_TIME", display: "Full-time" },
        { code: "PART_TIME", display: "Part-time" },
        { code: "CONTRACT", display: "Contract" },
        { code: "TEMPORARY", display: "Temporary" },
        { code: "INTERN", display: "Intern" },
      ],
    },
  ],
  exportFormats: ["json-ld", "json-schema"],
};
